version: '3'

vars:
  IMAGE_NAME: barca-informer
  CONTAINER_NAME: barca-informer

tasks:
  test:
    cmd: go test ./...
    desc: Run tests

  docker-build:
    cmds:
      - docker build -t {{.IMAGE_NAME}} .
    desc: Build docker image

  docker-stop:
    cmds:
      - docker rm -f {{.CONTAINER_NAME}} || true
    desc: Stop and remove old container

  docker-run:
    cmds:
      - docker run -d --name {{.CONTAINER_NAME}} --restart unless-stopped {{.IMAGE_NAME}}
    desc: Run docker container

  deploy:
    desc: Rebuild and restart app on server
    cmds:
      - task: docker-build
      - task: docker-stop
      - task: docker-run
